name: ci - linux binary cross build

on:
  workflow_call:
    outputs:
      release_tags:
        value: ${{ jobs.build.outputs.release_tags }}
    inputs:
      source_repo:
        type: string
        required: true
      source_branch:
        type: string
        required: true
    secrets:
      VT_API_KEY:
        required: false

env:
  GH_TOKEN: "${{ github.TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    outputs:
      release_tags: ${{ steps.release_tags.outputs.release_tag }}
    strategy:
      fail-fast: false
      matrix:
        name: [iperf3]
        os_id: [alpine]
        os_version_id: [edge]
        arch: [x86, x86_64, armhf, armv7, aarch64, ppc64le, riscv64, s390x]
        include:
          - arch: x86
            qbt-musl-cross-make: "i686-linux-musl"
            release_name: i386
          - arch: x86_64
            qbt-musl-cross-make: "x86_64-linux-musl"
            release_name: amd64
          - arch: armhf
            qbt-musl-cross-make: "armv6-linux-musleabihf"
            release_name: arm32v6
          - arch: armv7
            qbt-musl-cross-make: "armv6-linux-musleabihf"
            release_name: arm32v7
          - arch: armv7
            qbt-musl-cross-make: "armv7l-linux-musleabihf"
          - arch: aarch64
            qbt-musl-cross-make: "aarch64-linux-musl"
            release_name: arm64v8
          - arch: ppc64le
            qbt-musl-cross-make: "powerpc64le-linux-musl"
            release_name: ppc64le
          - arch: riscv64
            qbt-musl-cross-make: "riscv64-linux-musl"
            release_name: riscv64
          - arch: s390x
            qbt-musl-cross-make: "s390x-linux-musl"
            release_name: s390x

    name: ${{ matrix.name }} ${{ matrix.os_id }}:${{ matrix.os_version_id }} ${{ matrix.arch }}

    env:
      CDN: http://dl-cdn.alpinelinux.org/alpine/edge/main/
      CPPFLAGS: "-I/home/gh/local/include"
      CFLAGS: ""
      CXXFLAGS: ""
      LDFLAGS: "-static --static -L/home/gh/local/lib"
      source_repo: ${{ inputs.source_repo }}
      source_branch: ${{ inputs.source_branch }}
      container_name: mcm
      ws: ${{ github.workspace }}
      arch: ${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Host - Bootstrap qemu
        uses: userdocs/actions/qemu@main

      - name: Create docker ${{ env.container_name }} ${{ matrix.arch }} container
        run: >
          docker run --name ${container_name} -it -d -w /home/gh -v ${{ github.workspace }}:/home/gh
          -e CPPFLAGS="${{ env.CPPFLAGS }}"
          -e CFLAGS="${{ env.CXXFLAGS }}"
          -e CXXFLAGS="${{ env.CXXFLAGS }}"
          -e LDFLAGS="${{ env.LDFLAGS }}"
          ghcr.io/userdocs/musl-cross-make:${{ matrix.qbt-musl-cross-make }}

      - name: Run apk update
        run: docker exec ${container_name} apk update

      - name: Run apk upgrade
        run: docker exec ${container_name} apk upgrade

      - name: Iperf3 - Install openssl-static dependencies
        run: |
          docker exec ${container_name} cat /etc/apk/repositories > repositories.txt
          # checking if the containers is latest or edge so that we get the correct openssl libs
          cdn_repo="$(cat repositories.txt | sed -rn 's|https://dl-cdn.alpinelinux.org/alpine/(.*)/(.*)|\1|p' | head -1)"
          # Getting openssl packages info for the current arch and release
          openssl_libs_static=$(docker exec ${container_name} sh -c "apk info openssl-libs-static | head -1 | awk '{ print \$1 }'")
          openssl_dev=$(docker exec ${container_name} sh -c "apk info openssl-dev | head -1 | awk '{ print \$1 }'")
          # Downloading the openssl packages for the current arch and release
          curl -sLO "https://dl-cdn.alpinelinux.org/alpine/${cdn_repo}/main/${arch}/${openssl_dev}.apk"
          curl -sLO "https://dl-cdn.alpinelinux.org/alpine/${cdn_repo}/main/${arch}/${openssl_libs_static}.apk"
          # Extracting the openssl packages
          mkdir -p ${ws}/local
          tar -xzf "${openssl_dev}.apk" --strip-components=1 -C ${ws}/local
          tar -xzf "${openssl_libs_static}.apk" --strip-components=1 -C ${ws}/local

      - name: Git clone ${{ matrix.name }}
        run: docker exec -u gh:gh ${container_name} git clone --no-tags --single-branch --branch "${source_branch}" --shallow-submodules --recurse-submodules -j"$(nproc)" --depth 1 "${source_repo}" /home/gh/${{ matrix.name }}

      - name: Configure ${{ matrix.name }}
        run: docker exec -u gh:gh -w /home/gh/${{ matrix.name }} ${container_name} ./configure --with-openssl="/home/gh/local" --disable-shared --enable-static-bin --prefix="/home/gh/local"

      - name: Make Build ${{ matrix.name }}
        run: docker exec -u gh:gh -w /home/gh/${{ matrix.name }} ${container_name} make -j$(nproc)

      - name: Make Install Build ${{ matrix.name }}
        run: docker exec -u gh:gh -w /home/gh/${{ matrix.name }} ${container_name} make install

      - name: Rename ${{ matrix.name }} to ${{ matrix.name }}-${{ matrix.release_name }}
        run: docker exec -u gh:gh ${container_name} mv -f /home/gh/local/bin/${{ matrix.name }} /home/gh/${{ matrix.name }}-${{ matrix.release_name }}

      - name: Create path to binary env
        run: printf '%s\n' "binary_path=${{ github.workspace }}/${{ matrix.name }}-${{ matrix.release_name }}" >> $GITHUB_ENV

      - name: VirusTotal Scan
        id: virustotal
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: ${{ env.binary_path }}

      - name: sha256sum
        run: |
          printf '%s' https://www.virustotal.com/gui/file/$(sha256sum ${binary_path} | awk '{print $1}') > ${{ matrix.name }}-${{ matrix.release_name }}.url
          cat ${{ matrix.name }}-${{ matrix.release_name }}.url

      - name: Create tag env
        run: printf '%s\n' "release_tag=$(sed -rn 's|(.*)\[(.*)],\[https://github.com/esnet/iperf],(.*)|\2|p' ${{ matrix.name }}/configure.ac)" >> $GITHUB_ENV

      - name: Set tag env to output
        id: release_tags
        run: printf '%s\n' "release_tag=${release_tag}" >> "$GITHUB_OUTPUT"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ env.binary_path }}

      - name: "Create artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-${{ matrix.release_name }}
          path: |
            ${{ env.binary_path }}
            ${{ matrix.name }}-${{ matrix.release_name }}.url
